export const allBoardQuestionsDataArr = [
  // {
  //   board: "Dhaka Board",
  //   year: "2024",
  //   mark: "0.5x10=5",
  //   divider: "Part A Grammar Marks: 60",
  //   question_no: "1",
  //   question_title:
  //     "Fill in the blanks with the words from the box. You may need to change the form of some of the words. You may need to use one word more than once.",
  //   question_type: "Fill in the Blanks (with Clues)",
  //   clues: [
  //     "of",
  //     "out",
  //     "anglers",
  //     "into",
  //     "on",
  //     "of",
  //     "out",
  //     "anglers",
  //     "into",
  //     "on",
  //   ],
  //   question:
  //     "I am fond (a) ______ angling. Whenever I get time, I go. (b) _______ angling. On last Friday, I went to a big lake riear my village. I took (c) ________ angling rod, bait, (d) ______ umbrella, light (e) ______ and -some other necessary things for angling. I went there in the morning and spent the whole day. I threw the hook with bait at about 8 am (f) _______ the lake but no fish took the bait. I got a little disappointed. When I was about to leave the place, a big fish devoured (g) _____ bait. I felt spirited and let the hook loose for sometime and then I pulled it (h) ______. It was such a big fish that other (i) _______ gathered round the fish. (j) _________ I angled another three fishes and returned home with a happy mood.",
  // },
  {
    board: "Dhaka Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2025",
    mark: "0.5x10=5",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "1",
    question_title: "Complete the text with suitable prepositions:",
    question_type: "Preposition",
    question: [
      "Charity is a noble virtue. A person should be endowed (a) _______ this virtue. It makes people think fovourably (b) _______ their fellowmen and do them good. It is also the cheerful giving of one's possession to someone (c) _______ need. This quality brings happiness (d) _______ earth and strengthens the ties of relationship (e) _______ men. It should not be measured (f) _______ terms of money. Rather, it should be measured (g) _______ the sacrifice that one makes. In fact, it is a form (h) _______ self-sacrifice (i) _______ which our society cannot progress. So, everybody should practise this habit (j) _______ childhood.",
    ],
  },
  {
    board: "Dhaka Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2025",
    mark: "0.5x10=5",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "2",
    question_title:
      "Complete the sentences with suitable words/phrases given in the box:",
    question_type: "Suitable words or phrases",
    clues: [
      "let alone",
      "have to",
      "it",
      "was born",
      "as soon as",
      "there",
      "what's....like",
      "what does....look like",
      "had better",
      "would rather",
    ],
    question: [
      "(a) You ______ not touch the crocodile. It may be dangerous.",
      "(b) She has never boiled an egg. ______ prepared an entire meal.",
      "(c) It is raining outside. He will go to the shop ______ the rain stops.",
      "(d) I don't need a lift. I ______ walk.",
      "(e) They ______ solve these problems soon or the project will fail.",
      "(f) The house was dirty. ______ was John who cleaned the house.",
      "(g) ______ goes a proverb that morning shows the day.",
      "(h) ______ an alligator ______? I have never seen it.",
      "(i) He ______ of German parents. In fact, he lived most of his life abroad.",
      "(j) ______ the journey ______? It was very enjoyable to me.",
    ],
  },
  {
    board: "Dhaka Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2025",
    mark: "1x10=10",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "3",
    question_title:
      "Complete the following sentences with suitable clauses/phrases:",
    question_type: "Completing Sentence",
    subjectName: "English 2nd Paper",
    question: [
      "(a) Whenever I go to visit the factory, I _______. He must account for his absence.",
      "(b) You are now sick. Call me in case _______.",
      "(c) She confessed that _______. So he pardoned her.",
      "(d) It was very cold. They had to put on warm clothes so that _______.",
      "(e) The market is not far away from here. It will take them ten minutes _______.",
      "(f) The man tried heart and soul to get the job but could not. Had he got the job, _______.",
      "(g) Though we were thirsty _______, The water of the bottle was not pure.",
      "(h) They had to postpone their journey because of _______.",
      "(i) Man is a social being. So, he cannot always do whatever _______.",
      "(j) United we stand. _______.",
    ],
  },
  {
    board: "Dhaka Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2025",
    mark: "0.5x14=7",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "4",
    question_title:
      "Read the text and fill in the gaps with the correct forms of verbs as per subject and context:",
    question_type: "Right Forms of Verbs",

    question: [
      "In this world truth (a) _______ (reign) over falsehood. Those who are always in the habit of (b) _______ (speak) the truth (c) _______ (respect) everywhere. But those who are involved in telling lies (d) _______ (shine) in life. That is why, we see that many great men in the history used to (e) _______ (preach) truth among their countrymen. (f) _______ (be) truthful is essential for our society. It (g) _______ (hold) the highest value in (h) _______ (make) our society better. This quality (i) _______ (consider) as one of the essential factors that empower us from within. A truthful man is a (j) _______ (trust) person. And this trust (k) _______ (build) confidence in us. Confidence makes us (l) _______ (feel) better. When we start (m) _______ (get) comfortable with speaking the truth, we will begin to prosper. So, we should try hard (n) _______ (stay) away from the lies.",
    ],
  },
  {
    board: "Dhaka Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2025",
    mark: "7",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "5",
    question_title:
      "Change the narrative style of the following text by using indirect speeches:",
    question_type: "Narration",
    question: [
      '"Where are you going?" said the merchant, "I was coming to see you." "What do you want?" "To earn my bread by the labour of my hands." "Do you really want work?" said the merchant. "Yes, if you have any." Then follow me and carry a box from a shop to my house." "I do not see how I can do that," said the youth.',
    ],
  },
  {
    board: "Dhaka Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2025",
    mark: "0.5x10=5",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "6",
    question_title:
      "Read the following text and use modifiers in the blank spaces as directed:",
    question_type: "Modifiers",
    question: [
      "The necessity of learning English is the demand of today's world. But many people in (a) ________ (Pre-modify the noun with a possessive) country do not realize it. As we are living in (b) ________ (Pre-modify the noun with an adjective) village, it has become essential (c) ________ (Post-modify the adjective with an infinitive phrase). So, if we know English (d) ________ (Post-modify the verb with an adverb), we can communicate with people all over the world. Surely, English has become an important element of our (e) ________ (Use an adjective to pre-modify the noun) development. This language ensures us (f) ________ (Use an adjective to pre-modify the noun) access to all the information in the world computer (g) ________ (Use a participle phrase to pre-modify the clause), we can progress personally and professionally. If we fail to have a good command over the language, we will lag behind (h) ________ (Post-modify the verb using an adverbial). With (i) ________ (Use a demonstrative to pre-modify the noun) language, we can get access to art, literature and culture from various countries. So, it is clear that English is (j) ________ (Use an adverb to pre-modify the verb) spoken all over the world.",
    ],
  },
  {
    board: "Dhaka Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2025",
    mark: "0.5x14=7",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "7",
    question_title:
      "Use appropriate sentence connectors in the blank spaces of the following text:",
    question_type: "Connectors",
    question: [
      "A thing of beauty is a joy forever. (a) ________ a flower is a symbol of beauty and purity. (b) ________ flower cultivation was rare in our country. (c) ________ the scenario has been changed. (d) ________ people cultivate flowers not only for enjoying their beauty but also for earning money. (e) ________, in big cities and towns, many flower shops have flourished and different types of flowers are sold there. (f) ________, the demand of flowers is increasing day by day. (g) ________, they are of great use to us. (h) ________, flowers play an important role in making our mood cheerful and happy. (i) ________, they are used for decorating homes. (j) ________, flowers are regarded as a symbol of mourning and tribute to someone. (k) ________, in many popular and special events, flowers are needed for stage or spot decoration. (l) ________, we express our love and affection towards anyone with flowers. (m) ________, flowers are a great source of honey, perfume, medicine and even food. (n) ________, the use of flowers in our daily life has become wide in different ways.",
    ],
  },
  {
    board: "Dhaka Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2025",
    mark: "0.5x14=7",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "8",
    question_title:
      "Read the passage and then write the antonym or synonym of the words as directed:",
    question_type: "Antonym or Synonym",
    clues: [
      `There can be no /progress| without /efforts|. Life loses its /interest| if there is no /struggle|. For example, games become /dull| if there is no /competition| in them and if the result is /easily| foreseen. No matter we /win| the game or lose it. The keener the contest, the greater the /enjoyment|. A /victory| is not a /real| triumph unless both the sides are /equally| matched. Whether we /like| it or not, life is a /continuous| competitive examination.`,
    ],
    question: [
      "(a) progress – (synonym)",
      "(b) efforts – (synonym)",
      "(c) interest – (synonym)",
      "(d) struggle – (antonym)",
      "(e) dull – (antonym)",
      "(f) competition – (synonym)",
      "(g) easily – (antonym)",
      "(h) win – (antonym)",
      "(i) enjoyment – (synonym)",
      "(j) victory – (antonym)",
      "(k) real – (synonym)",
      "(l) equally – (antonym)",
      "(m) like – (synonym)",
      "(n) continuous – (antonym)",
    ],
  },
  {
    board: "Dhaka Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2025",
    mark: "0.5x14=7",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "9",
    question_title:
      "There are fourteen errors in the use of punctuation marks in the following text. Re-write the text correcting the errors and use capital letters if necessary:",
    question_type: "Punctuation and Capitalization",
    question: [
      "Kamal : Wheres your pen?",
      "Rony : It's gone.",
      "Kamal : Gone",
      "Rony : Yes it was on the desk a few minutes ago Now there in no sign of it.",
      "Kamal : I left it on the desk.",
      "Rony : Its my favourite pen. What can I do",
      "Kamal : Lets complain to the Principal.",
      "Rony : For what",
      "Kamal : For your pen",
      "Rony : Youre mad I'll complain to the Principal for a pen",
    ],
  },
  {
    board: "Dhaka Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2025",
    mark: "10",
    partName: "Part B: Composition || Marks: 40",
    part: "b",
    question_no: "10",
    question_title:
      "Suppose you are a student of a college in Dhaka. Many outsiders disturb the students in your college campus during class hours. Now, on behalf of the students, write an application to your Principal for taking measures against the outsiders.",
    question_type: "Application",
    question: [
      "Suppose you are a student of a college in Dhaka. Many outsiders disturb the students in your college campus during class hours. Now, on behalf of the students, write an application to your Principal for taking measures against the outsiders.",
    ],
  },
  {
    board: "Dhaka Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2025",
    mark: "15",
    partName: "Part B: Composition || Marks: 40",
    part: "b",
    question_no: "11",
    question_title: `Write a paragraph on "The Importance of Moral Values" within 200 words.`,
    question_type: "Paragraph",
    question: [
      `Write a paragraph on "The Importance of Moral Values" within 200 words.`,
    ],
    type: "",
  },
  {
    board: "Dhaka Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2025",
    mark: "15",
    partName: "Part B: Composition || Marks: 40",
    part: "b",
    question_no: "12",
    question_title: `Write a paragraph on "Frequent Road Accidents—It's Causes and Effects in Bangladesh" within 200 words.`,
    question_type: "Paragraph",
    question: [
      `Write a paragraph on "Frequent Road Accidents—It's Causes and Effects in Bangladesh" within 200 words.`,
    ],
    type: "Cause and Effect Paragraph",
  },
  // another
  {
    board: "Mymensingh Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2024",
    mark: "15",
    partName: "Part B: Composition || Marks: 40",
    part: "b",
    question_no: "12",
    question_title: `Write a paragraph on 'Price Hike'.`,
    question_type: "Paragraph",
    question: [`Write a paragraph on 'Price Hike'.`],
    type: "",
  },
  {
    board: "Mymensingh Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2024",
    mark: "0.5x10=5",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "1",
    question_title: "Complete the text with suitable prepositions:",
    question_type: "Preposition",
    question: [
      "Ours is a riverine country. Rivers are everywhere (a) ___ But are the rivers (b) ___ our life, literature, economy and culture. several are going (c) ___ the pangs of ? A report published in 'The Daily Sun' describes what Buriganga is an example (d) ___ the rivers. A report published in the 'The Daily Sun' describes what has happened (e) ___ the Buriganga and why. Its water is polluted and a perpetual stench fills the air (f) ___ it. Once it was a tributary (g) ___ Ganges and got the name Buriganga. It is (h) ___ present a dying river but once it flowed (i) ___ the river Dhaleshwari. Gradually, it has lost its link (j) ___ the river.",
    ],
  },
  {
    board: "Mymensingh Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2024",
    mark: "0.5x10=5",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "2",
    question_title:
      "Complete the sentences with suitable words/phrases given in the box:",
    question_type: "Suitable words or phrases",
    clues: [
      "there",
      "has to",
      "let alone",
      "as soon as",
      "what does....look like",
      "was born",
      "it",
      "had better",
      "would rather",
      "what's....like",
    ],
    question: [
      "(a) Selina is a poor student. She cannot afford to buy a cell phone ———— a laptop.",
      "(b) The sky is cloudy. It may rain today. You ———— leave early.",
      "(c) ——— is many years since we first met. How time does fly!",
      "(d) His mother is sick. He needs to go home ———— possible.",
      "(e) We ———-develop our humanity than observe hartal and strike.",
      "(f) Robert Browning is my favorite poet. He ——— in 1812.",
      "(g) ———— was a pandemic all over the world in 2020 and 2021.",
      "(h) A good citizen ———— perform a lot of things.",
      "(i) The national flower of Bangladesh ————?",
      "(j) ——— honesty ———-? It is the best quality of life.",
    ],
  },
  {
    board: "Mymensingh Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2024",
    mark: "1x10=10",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "3",
    question_title:
      "Complete the following sentences with suitable clauses/phrases:",
    question_type: "Completing Sentence",

    question: [
      "(a) Patriotism is a noble virtue. It is high time ———.",
      "(b) Hasan got GPA 4.50. Had he studies seriously he ————.",
      "(c) Time is valuable, Those who waste time ————.",
      "(d) This celling is not so high. He is tall enough ————.",
      "(e) Lock the door and keep the key in a safe place lest ————.",
      "(f) You cannot understand everything clearly unless ————.",
      "(g) A lot of passengers were waiting at the bus stop. A bus came. But the bus was so small that —————.",
      "(h) Inspite of facing so many drawbacks in life he ———— ultimately.",
      "(i) Ayesha is a bright student. She studies hard so that —————.",
      "(j) Freedom is man's birth right. He is born free but every where ————.",
    ],
  },
  {
    board: "Mymensingh Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2024",
    mark: "0.5x14=7",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "4",
    question_title:
      "Read the text and fill in the gaps with the correct forms of verbs as per subject and context:",
    question_type: "Right Forms of Verbs",

    question: [
      "Man has unquenchable thirst for knowledge. He is never (a) ——— (satisfy) with what he already (b) ———(know) and (c)———— (see). Naturally he (d) ———— (want) to know and (e) ——— (see) more and more. This curiosity for (f) ——— (know) more has (g) ———— (inspire) him (h)———— (undertake) and (i)———— (carry) out difficult and dangerous tasks which eventually (j) ——— (result) in epoch making discoveries and inventions and (k)——— (lead) him in his long and continuous journey from his helpless state of caveman to his present situations of power and progress. He (l) ———— (be) helpless still now, he would not have (m) ———— (be) able to control all powers and forces. (n)————(invent) so many technologies he now controls almost all destructive powers and forces.",
    ],
  },
  {
    board: "Mymensingh Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2024",
    mark: "7",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "5",
    question_title:
      "Change the narrative style of the following text by using indirect speeches:",
    question_type: "Narration",
    question: [
      `The king said to the astrologer, “How long do you want to live? For you will be hanged very soon." Looking at the sky the astrologer said, "My Lord, the positions of the stars declare that I'II die only a week before your Majesty. Good bye." The king turned pale and ordered his courtiers, "Drive this wretch away and never allow him to come for disturbing peace."`,
    ],
  },
  {
    board: "Mymensingh Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2024",
    mark: "0.5x10=5",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "6",
    question_title:
      "Read the following text and use modifiers in the blank spaces as directed:",
    question_type: "Modifiers",
    question: [
      `A library is a (a) —— (pre-modify the noun) house of knowledge. The students (b) —— (use a participle) in all classes visit it in their leisure period. Usually a college library is housed in two rooms. (c) —— (pre-modify the noun) almirahs are placed in one room. The other room is the (d) —— (use a participle to modify the noun) room where magazines, Journals and newspapers are placed. Hundreds of books are arranged (e) —— (post-modify the verb). So any type of book can be traced in no time. The books cater to the needs and interests (f) —— (use a pre-positional phrase). Generally there are two separate sections in the library. One of them contains reference books like (g) ——— (use nouns) etc. The other section contains books (h) ——— (use a pre-positional phrase). Every student has a (i) —— (use a noun adjective to modify noun) card. The reading room is always crowded (j) —— (post modify the verb) in the afternoon.`,
    ],
  },
  {
    board: "Mymensingh Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2024",
    mark: "0.5x14=7",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "7",
    question_title:
      "Use appropriate sentence connectors in the blank spaces of the following text:",
    question_type: "Connectors",
    question: [
      "A library is a (a) —— (pre-modify the noun) house of knowledge. The students (b) —— (use a participle) in all classes visit it in their leisure period. Usually a college library is housed in two rooms. (c) —— (pre-modify the noun) almirahs are placed in one room. The other room is the (d) —— (use a participle to modify the noun) room where magazines, Journals and newspapers are placed. Hundreds of books are arranged (e) —— (post-modify the verb). So any type of book can be traced in no time. The books cater to the needs and interests (f) —— (use a pre-positional phrase). Generally there are two separate sections in the library. One of them contains reference books like (g) ——— (use nouns) etc. The other section contains books (h) ——— (use a pre-positional phrase). Every student has a (i) —— (use a noun adjective to modify noun) card. The reading room is always crowded (j) —— (post modify the verb) in the afternoon.",
    ],
  },
  {
    board: "Mymensingh Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2024",
    mark: "0.5x14=7",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "8",
    question_title:
      "Read the passage and then write the antonym or synonym of the words as directed:",
    question_type: "Antonym or Synonym",
    clues: [
      `Sincerity is the essential element of life. Since it is the root of /success| it is the quality of /great| men. They know its /importance| in human life. A sincere person is concerned about the /outcome| of his deeds. He has a good /intention|. People would like to /trust| a sincere person as he does not /prove| false. So, he usually, wins /respect| of others. A sincere person is always /eager| to possess a truthful mind. friendly and real personality. With these qualities he can /overcome| many difficulties in life. He can also recognize the intrinsic /value| of something. His good /deeds| are recognized and /praised| everywhere. Undoubtedly a /sincere| person is a trustworthy person.`,
    ],
    question: [
      "(a) success (antonym)",
      "(b) great (antonym)",
      "(c) importance (synonym)",
      "(d) outcome (synonym)",
      "(e) intention (synonym)",
      "(f) trust (antonym)",
      "(g) respect (antonym)",
      "(h) eager (antonym)",
      "(i) prove (synonym)",
      "(j) overcome (synonym)",
      "(k) value (synonym)",
      "(l) deed (synonym)",
      "(m) praise (antonym)",
      "(n) sincere (synonym)",
    ],
  },
  {
    board: "Mymensingh Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2024",
    mark: "0.5x14=7",
    partName: "Part A: Grammar || Marks: 60",
    part: "a",
    question_no: "9",
    question_title:
      "There are fourteen errors in the use of punctuation marks in the following text. Re-write the text correcting the errors and use capital letters if necessary:",
    question_type: "Punctuation and Capitalization",
    question: [
      "Rahim : We are about to finish our HSC examination are you thinking about your future",
      "Karim: Yes, What about you",
      "Rahim: I want to pursue higher education. What are your plans",
      "Karim : I rather follow some vocation course to make my career.",
      "Rahim : Really have you thought of any particular vacation",
      "Karim: Yes I would like to join the fashion design course. This career has a prospect these days.",
      "Rahim: It is suitable for boys.",
      "Karim: Why not Boys are as good as girl in many profession now a days. Whats your future plan",
      "Rahim: I would like to no for teaching.",
      "Karim: its good profession far a studious boy like you.",
    ],
  },
  {
    board: "Mymensingh Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2024",
    mark: "10",
    partName: "Part B: Composition || Marks: 40",
    part: "b",
    question_no: "10",
    question_title:
      "Write an application to the Principal of your college to install multimedia system in the classroom.",
    question_type: "Application",
    question: [
      "Write an application sto the Principal of your college to install multimedia system in the classroom.",
    ],
  },
  {
    board: "Mymensingh Board",
    subjectName: "English 2nd Paper",
    examName: "hsc",
    year: "2024",
    mark: "15",
    partName: "Part B: Composition || Marks: 40",
    part: "b",
    question_no: "11",
    question_title: `Write a paragraph on uses and abuses of internet in 200 words.`,
    question_type: "Paragraph",
    question: [
      `Write a paragraph on uses and abuses of internet in 200 words.`,
    ],
    type: "",
  },
];
/* 

we dont need board_id

*/
